# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BUILD_SOURCE_DIRS "/home/saad-saeed/qgroundcontrol;/home/saad-saeed/qgroundcontrol/build-release")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "Unspecified;liblzma_Development")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/home/saad-saeed/Qt/6.10.0/Tools/CMake/share/cmake-3.30/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "QGroundControl built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TGZ")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/saad-saeed/qgroundcontrol/build-release;QGroundControl;ALL;/")
set(CPACK_INSTALL_PREFIX "/home/saad-saeed/qgroundcontrol/build-release/AppDir/usr")
set(CPACK_MODULE_PATH "/home/saad-saeed/qgroundcontrol/cmake;/home/saad-saeed/qgroundcontrol/cmake/CPack;/home/saad-saeed/qgroundcontrol/cmake/find-modules;/home/saad-saeed/qgroundcontrol/cmake/install;/home/saad-saeed/qgroundcontrol/cmake/install/CPack;/home/saad-saeed/qgroundcontrol/cmake/modules;/home/saad-saeed/qgroundcontrol/cmake/platform;/home/saad-saeed/qgroundcontrol/custom/cmake;/home/saad-saeed/Qt/6.10.0/6.10.1/gcc_64/lib/cmake/Qt6;/home/saad-saeed/Qt/6.10.0/6.10.1/gcc_64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/saad-saeed/Qt/6.10.0/6.10.1/gcc_64/lib/cmake/Qt6/3rdparty/kwin;/home/saad-saeed/Qt/6.10.0/6.10.1/gcc_64/lib/cmake/Qt6;/home/saad-saeed/Qt/6.10.0/6.10.1/gcc_64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/saad-saeed/Qt/6.10.0/6.10.1/gcc_64/lib/cmake/Qt6/3rdparty/kwin")
set(CPACK_NSIS_DISPLAY_NAME "GeographicLib-2.7")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "GeographicLib-2.7")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/saad-saeed/qgroundcontrol/build-release/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "karney@alum.mit.edu")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/saad-saeed/Qt/6.10.0/Tools/CMake/share/cmake-3.30/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "GeographicLib library, utilities, and documentation")
set(CPACK_PACKAGE_FILE_NAME "QGroundControl-2.7-Linux")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://qgroundcontrol.com")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "GeographicLib-2.7")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "GeographicLib-2.7")
set(CPACK_PACKAGE_NAME "QGroundControl")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "GeographicLib")
set(CPACK_PACKAGE_VERSION "2.7")
set(CPACK_PACKAGE_VERSION_MAJOR "2")
set(CPACK_PACKAGE_VERSION_MINOR "7")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/saad-saeed/qgroundcontrol/.cpm_cache/geographiclib/e033/LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "/home/saad-saeed/Qt/6.10.0/Tools/CMake/share/cmake-3.30/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/home/saad-saeed/Qt/6.10.0/Tools/CMake/share/cmake-3.30/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "#;~$;/\\.git;/home/saad-saeed/qgroundcontrol/.cpm_cache/geographiclib/e033/BUILD;/home/saad-saeed/qgroundcontrol/.cpm_cache/geographiclib/e033/man/(.*\\.pod|makeusage\\.sh|dummy\\..*)$;/home/saad-saeed/qgroundcontrol/.cpm_cache/geographiclib/e033/cmake/maintainer-.*\\.cmake$;/home/saad-saeed/qgroundcontrol/.cpm_cache/geographiclib/e033/(develop|cgi-bin|.*\\.cache)/;/home/saad-saeed/qgroundcontrol/.cpm_cache/geographiclib/e033/(data-distrib|data-installer)/;/home/saad-saeed/qgroundcontrol/.cpm_cache/geographiclib/e033/(archive|scratch|mpfr_mpir_x86_x64_msvc2010)/;/home/saad-saeed/qgroundcontrol/.cpm_cache/geographiclib/e033/.*\\.(zip|tar\\.gz|bak|lsp)$;/home/saad-saeed/qgroundcontrol/.cpm_cache/geographiclib/e033/autogen\\.sh$;/home/saad-saeed/qgroundcontrol/.cpm_cache/geographiclib/e033/include/mpreal\\.h$;/home/saad-saeed/qgroundcontrol/.cpm_cache/geographiclib/e033/maxima/auxvals40\\.mac$;/home/saad-saeed/qgroundcontrol/.cpm_cache/geographiclib/e033/(makefile-admin|HOWTO-RELEASE.txt)$")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/saad-saeed/qgroundcontrol/build-release/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "GeographicLib-2.7")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/saad-saeed/qgroundcontrol/build-release/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
