
set(target "AppSettingsModule")
set(working_dir "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings")
set(src_and_dest_list
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/ADSBServerSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/ADSBServerSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/BluetoothSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/BluetoothSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/DebugWindow.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/DebugWindow.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/FlyViewSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/FlyViewSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/GeneralSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/GeneralSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/HelpSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/HelpSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/LinkSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/LinkSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/LogReplaySettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/LogReplaySettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/MapSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/MapSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/NTRIPSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/NTRIPSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/MockLink.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/MockLink.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/MockLinkSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/MockLinkSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/PlanViewSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/PlanViewSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/PX4LogTransferSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/PX4LogTransferSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/QmlTest.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/QmlTest.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/RemoteIDSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/RemoteIDSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/SerialSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/SerialSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/SettingsPage.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/SettingsPage.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/SettingsPagesModel.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/SettingsPagesModel.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/TcpSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/TcpSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/TelemetrySettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/TelemetrySettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/UdpSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/UdpSettings.qml"
    "/home/saad-saeed/qgroundcontrol/src/UI/AppSettings/VideoSettings.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/AppSettings/VideoSettings.qml"

)
set(timestamp_file "/home/saad-saeed/qgroundcontrol/build-release/src/UI/AppSettings/.qt/AppSettingsModule_qml.txt")
