
set(target "Viewer3DModule")
set(working_dir "/home/saad-saeed/qgroundcontrol/src/Viewer3D")
set(src_and_dest_list
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Viewer3D.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Viewer3D.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Models3D/CameraLightModel.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Models3D/CameraLightModel.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Models3D/Viewer3DModel.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Models3D/Viewer3DModel.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/DroneModelDjiF450.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/DroneModelDjiF450.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_arm_1/DroneModel_arm_1.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_arm_1/DroneModel_arm_1.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_arm_2/DroneModel_arm_2.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_arm_2/DroneModel_arm_2.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_arm_3/DroneModel_arm_3.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_arm_3/DroneModel_arm_3.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_arm_4/DroneModel_arm_4.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_arm_4/DroneModel_arm_4.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_BLDC_1/DroneModel_BLDC_1.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_BLDC_1/DroneModel_BLDC_1.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_BLDC_2/DroneModel_BLDC_2.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_BLDC_2/DroneModel_BLDC_2.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_BLDC_3/DroneModel_BLDC_3.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_BLDC_3/DroneModel_BLDC_3.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_BLDC_4/DroneModel_BLDC_4.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_BLDC_4/DroneModel_BLDC_4.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_propeller2_2/DroneModel_propeller2_2.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_propeller2_2/DroneModel_propeller2_2.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_propeller2_7/DroneModel_propeller2_7.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_propeller2_7/DroneModel_propeller2_7.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_propeller22_1/DroneModel_propeller22_1.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_propeller22_1/DroneModel_propeller22_1.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_propeller22_2/DroneModel_propeller22_2.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_propeller22_2/DroneModel_propeller22_2.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_Base_bottom_1/DroneModel_Base_bottom_1.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_Base_bottom_1/DroneModel_Base_bottom_1.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_Base_Top_1/DroneModel_Base_Top_1.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_Base_Top_1/DroneModel_Base_Top_1.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Models3D/Waypoint3DModel.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Models3D/Waypoint3DModel.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Models3D/Line3D.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Models3D/Line3D.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Models3D/Viewer3DVehicleItems.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Models3D/Viewer3DVehicleItems.qml"
    "/home/saad-saeed/qgroundcontrol/src/Viewer3D/Viewer3DQml/Viewer3DProgressBar.qml"
    "/home/saad-saeed/qgroundcontrol/build-release/qml/QGroundControl/Viewer3D/Viewer3DQml/Viewer3DProgressBar.qml"

)
set(timestamp_file "/home/saad-saeed/qgroundcontrol/build-release/src/Viewer3D/.qt/Viewer3DModule_qml.txt")
